version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27018:27017
    volumes:
      - mongodb_data_container:/data/db

  mysql_container:
      image: mysql:latest
      container_name: shop-dev
      restart: always
      hostname: mysql02
      ports:
        - "33062:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=123
        - MYSQL_DATABASE=dev
        - MYSQL_USER=dev
        - MYSQL_PASSWORD=123
      # command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
      # volumes:
      #   - ./db/dbdata:/var/lib/mysql
      #   - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      # networks:
      #   - default

volumes:
  mongodb_data_container: